version: "3"
services:
    database:
      image: postgres:13-alpine
      ports:
        - 5432:5432 
      restart: on-failure
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=postgres
    
    server:
      build:
        context: .
        dockerfile: server.dockerfile
      ports:
        - 8080:8080
      environment:
        - DB_PASS=postgres
        - DB_USER=postgres
        - DB_SCHEMA=postgres
        - DB_HOST=database
        - DB_SSL=false
        - DB_PORT=5432